source "https://rubygems.org"
ruby "2.2.5"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use mysql as the database for Active Record
gem 'mysql2', '0.3.18' # Use SCSS for stylesheets
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

#新しく以下を加えました。
# gem 'twitter-bootstrap-rails'
# gem 'bootstrap-sass', '~> 3.2.0'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end


  # Access an IRB console on exception pages or by using <%= console %> in views
gem 'web-console'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring'
gem 'mechanize'
gem 'pry-rails'
gem 'devise','4.1.0'
gem 'kaminari'
gem 'therubyracer'
gem 'twitter-bootstrap-rails'
gem 'bootstrap-material-design', '0.1.4'
gem 'enum_help'
gem 'jQuery-Validation-Engine-rails'
gem 'rails-i18n'
gem 'rails4-autocomplete'
gem 'autonumeric-rails'
gem 'compass-rails', '~> 2.0.alpha.0'
gem 'chosen-rails'
gem 'momentjs-rails', '>= 2.9.0'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.37'
gem 'jquery-ui-rails'
gem 'ransack'
gem 'carrierwave'
gem 'rmagick', require: 'RMagick'
group :production, :staging do
  gem 'rails_12factor'
end
gem 'jquery-turbolinks'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
#gem 'bootstrap-sass', '~> 3.2.0'

