# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1e09b07b937d51e2b278be2df74659bf2bad8d5f2c17b32f513f3cbebfa63aadb85604e4ebe26ec9bb9998ceb29b24399ed6432f7b3cbfa4782b8960556f512

test:
  secret_key_base: 663b724fb7789bc6071aae7ffce97f6b5337cc796f89452fd4882b457d4a5c4d286c684bf82a45218a963543543fba1939a48e1602495bb89032d27be8e71459

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
