# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a508df21566e38693f3ff07bf4d2b41c12fd7213e4e1e02b602bdb31887d46b7fa8e4bb1377b33d2e7baf7e54ab01427ffa9b3a64f4ff38f78054ed2cf455caf

test:
  secret_key_base: acdc22e57f378ac49d8a50a7fc00a482280871112b1d8fed80a5e5231cff61f4179540299f21857370782082774e99067700bda650287934558da9d152ac7f9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
